### ISSUE TITLE
Explore events' flow in Cloudstack + Cloudstack UI

### ISSUE THREAD

**Issue by Krisilda** [bwsw/cs-vault-server#1]
1) Create a list of all possible events which can be processed with Vault. 
2) Make all actions from the list and study how events are recorded to Kafka and how to read out events from Kafka.

**Comment by MedvedevBW** [comment]
1. Vault's events: 
a) Token and ACL(policy) creating (for user or VM).
b) Token and ACL deleting (for user or VM).

**Comment by MedvedevBW** [comment]
2) Records in kafka is auto creating with events of creating User or VM in ACS. The org.apache.kafka lib will be use for reading events from kafka
