### ISSUE TITLE
ConsumerManager constructor redesign

### ISSUE THREAD

**Issue by bwsw** [bwsw/cs-vault-server#43]
What is the purpose to accept by
```
class ConsumerManager(topic: String, brokers: String, components: Components)
```
topic, brokers, components parameters. I don't see the purpose. You are mixing levels of abstraction. Fix it.

**Comment by MedvedevBW** [comment]
This has already been fixed, but has not been pushed into "master" branch.

**Comment by placccebo** [comment]
@bwsw 
it looks like this "class ConsumerManager[T](eventHandler: EventHandler[T], settings: ConsumerManager.Settings)" in develop, maybe you met this in  master
