### ISSUE TITLE
What is the purpose of the class with empty functionality?

### ISSUE THREAD

**Issue by bwsw** [bwsw/cs-vault-server#46]
https://github.com/bwsw/cs-vault-server/blob/8bdb28ca6ff018cca62c6e73cfbe8e686bfb874f/src/main/scala/com/bwsw/cloudstack/vault/server/cloudstack/CloudStackService.scala#L6

Fix it.

**Comment by MedvedevBW** [comment]
@bwsw 
This class is implemented in "develop" branch.
