### ISSUE TITLE
Rename meaningless method "isDefinedAt" to meaningful

### ISSUE THREAD

**Issue by bwsw** [bwsw/cs-vault-server#48]
https://github.com/bwsw/cs-vault-server/blob/8bdb28ca6ff018cca62c6e73cfbe8e686bfb874f/src/main/scala/com/bwsw/cloudstack/vault/server/cloudstack/util/CloudStackEventHandler.scala#L43

**Comment by MedvedevBW** [comment]
I can not do this, it's an override method. It is used as default method in PartialFunction

**Comment by bwsw** [comment]
Ok, got it.
