### ISSUE TITLE
Compare names

### ISSUE THREAD

**Issue by bwsw** [bwsw/cs-vault-server#53]
https://github.com/bwsw/cs-vault-server/blob/7110f5d1ccef01edcd729635d40f54d28527cd50/src/main/scala/com/bwsw/cloudstack/vault/server/cloudstack/CloudStackService.scala#L88

```
getVmTagsById
getAccountIdByVmId
```

```
getVmTags
getVmOwnerAccount
```

**Comment by MedvedevBW** [comment]
It was fixed in #52
