### ISSUE TITLE
Fix bad English everywhere

### ISSUE THREAD

**Issue by bwsw** [bwsw/cs-vault-server#54]
https://github.com/bwsw/cs-vault-server/blob/7110f5d1ccef01edcd729635d40f54d28527cd50/src/main/scala/com/bwsw/cloudstack/vault/server/cloudstack/CloudStackService.scala#L94

"Tags were got" is a wrong phrase, use something like "Tags retrieved". I don't think that passive voice in the past are best way to express such great outcome. If you DO debug, why don't you debug actual TAGS that retrieved. What is the case to use such useless debug information??? FIX everywhere.

**Comment by MedvedevBW** [comment]
@bwsw 
Because tag include token, and I'm afraid to show the token in the logs.

**Comment by bwsw** [comment]
It's debug. It's for admins. Admins know even root token, what's wrong? It's not info, etc, it's debug.
