### ISSUE TITLE
Fix English everywhere in function annotations

### ISSUE THREAD

**Issue by bwsw** [bwsw/cs-vault-server#61]
https://github.com/bwsw/cs-vault-server/blob/7110f5d1ccef01edcd729635d40f54d28527cd50/src/main/scala/com/bwsw/cloudstack/vault/server/cloudstack/CloudStackService.scala#L63

**Comment by bwsw** [comment]
"Retrieves tag values for user objects" is it not easy enough to write just like that? Do you really need to write tongue twisters? I even put it into google translate and it did great translation:
https://goo.gl/wuK2Aa

**Comment by MedvedevBW** [comment]
Was fixed in #54
