### ISSUE TITLE
What is the purpose to use exception inside exception. Fix It.

### ISSUE THREAD

**Issue by bwsw** [bwsw/cs-vault-server#62]
https://github.com/bwsw/cs-vault-server/blob/7110f5d1ccef01edcd729635d40f54d28527cd50/src/main/scala/com/bwsw/cloudstack/vault/server/cloudstack/CloudStackService.scala#L114

**Comment by MedvedevBW** [comment]
@bwsw 
CloudStackCriticalException extends CriticalException, and CriticalException needs for exceptions handling in Consumer.

**Comment by bwsw** [comment]
@MedvedevBW please provide widely known exception handling code pattern which uses that approach.

**Comment by bwsw** [comment]
@MedvedevBW understanding that you can do something doesn't mean you should do it without a high motivation. You don't create the code because you can, you do it for people.
