### ISSUE TITLE
Update documentation in GitHub wi-ki

### ISSUE THREAD

**Issue by Krisilda** [bwsw/cs-vault-server#99]
1. Create Page 'Version 4.9.3' and move current documentation there. 
2. Create page 'Version 4.10.3-NP' and make changelog description for this version.

**Comment by MedvedevBW** [comment]
@Krisilda 
https://github.com/bwsw/cs-vault-server/wiki/Version-4.10.3-NP
https://github.com/bwsw/cs-vault-server/wiki/Version-4.9.3

**Comment by Krisilda** [comment]
Needed changes:
1. Delete page Application proposal.
2. Move Requirements description from Page Version 4.10.3 to the appropriate page Requirements.
3. Update information on page Requirements (my task). 
4. Page Version 4.10.3 NP should be placed after page Version 4.9.3 in the table of contents.
5. Move /docs/logic.md to the wi-ki? (need coordination with Ivan).
6. Version 4.10.3 NP doesn't fully described. Please add a link to the place where a user can find a description of logic (according to a resolution of the 5th step above).

**Comment by MedvedevBW** [comment]
1. Done
2. Which milestone in?
3. -
4. Wiki is using auto sorting
5. -
6. Updated
